# Generated by Django 4.2.6 on 2023-10-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaPlusapp', '0002_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
