# Generated by Django 4.2.6 on 2023-10-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaPlusapp', '0003_projeto_descricao_alter_projeto_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
