# Generated by Django 4.1.7 on 2023-10-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaPlusapp', '0004_alter_projeto_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='voluntarios/')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
