# Generated by Django 4.2.1 on 2023-10-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaPlusapp', '0005_usuario_delete_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
